version: '3.5'

services:
    frontend:
        build: 
            context: .
            dockerfile: Dockerfile_frontend
        container_name: frontend_10   
        ports:
            - 5000:5000
        environment:
            - API_URL=/api/
    backend:
        container_name: backend_10
        build: 
            context: .
            dockerfile: Dockerfile_backend
        ports:
            - 8000:8000
        environment:
            - REDIS=redis
            - DB_NAME=testDatabase
            - DB_USERNAME=admin
            - DB_PASSWORD=test12345!
            - DB_HOST=postgres
            - FRONT_URL=http://localhost/
        volumes:
            - ./logs.txt:/usr/app/logs.txt
        depends_on: 
            - postgres
    redis:
        container_name: redis_backend_10
        image: redis
    postgres:
        image: postgres
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=test12345!
            - POSTGRES_DB=testDatabase 
        container_name: db_backend_10 
        volumes:
            - postgres_persistent_data:/var/lib/postgresql/data
        restart: unless-stopped
    nginx:
        image: nginx
        container_name: nginx_10
        ports:
            - 80:80
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
volumes:
    postgres_persistent_data:

