version: '3.5'

services:
        frontend:
                build:
                        context: https://github.com/docker-hy/ml-kurkkumopo-frontend.git
                container_name: frontend_7
                ports:
                        - 3000:3000
                

        backend:
                build:
                        context: https://github.com/docker-hy/ml-kurkkumopo-backend.git
                container_name: backend_7
                ports: 
                        - 5000:5000
                volumes:
                        - model:/src/model

        training:
                build:
                        context: https://github.com/docker-hy/ml-kurkkumopo-training.git
                container_name: training_7
                volumes:
                        - imgs:/src/imgs
                        - model:/src/model
volumes:
        imgs:
        model:
